column_width = 200
line_endings = "Unix"
indent_type = "Spaces"
indent_width = 4
quote_style = "ForceSingle"
call_parentheses = "Input"
collapse_simple_statement = "Never"

[sort_requires]
enabled = false
